# Source: java/charts/appdirect/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdirect
  namespace: mobility-zimperium-apps
  labels:
    dwp.gov.uk-application: zimperium
    dwp.gov.uk-environment: test
    dwp.gov.uk-function: mobility
    app: appdirect
    chart: appdirect-0.1.0
    release: java
    heritage: Helm
    manifest_version: abc
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: appdirect
      release: java
  template:
    metadata:
      labels:
        dwp.gov.uk-application: zimperium
        dwp.gov.uk-environment: test
        dwp.gov.uk-function: mobility
        app: appdirect
        release: java
        manifest_version: abc
        app_tag: 12.3.0
    spec:
      securityContext:  # Added security context for the pod
        runAsUser: 10000
        runAsGroup: 20000
        fsGroup: 20000
        readOnlyRootFilesystem: false
      imagePullSecrets:
        - name: regcred
      containers:
        - name: appdirect
          image: "943009210227.dkr.ecr.eu-west-2.amazonaws.com/pdu-test/tenant/mobility-zimperium/appdirect:12.3.0"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
          env:
            - name: MANAGEMENT_METRICS_EXPORT_STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: COM_ZIMPERIUM_SERVER_APPDIRECT_SERVICES_TENANT
              value: http://tenant:8080/api
            - name: COM_ZIMPERIUM_SERVER_APPDIRECT_SERVICES_USER
              value: http://user:8080/api
            - name: COM_ZIMPERIUM_SERVER_APPDIRECT_SERVICES_DEVICE
              value: http://device:8080/api
            - name: JVM_HEAP_OPTS
              value: " "
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            failureThreshold: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              ephemeral-storage: 4Gi
              memory: 1024Mi
            requests:
              cpu: 100m
              ephemeral-storage: 2Gi
              memory: 512Mi
